# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aws_session.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'aws_session.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61ws_session.proto\"p\n\x08UserInfo\x12\x16\n\x0e\x65ncrypt_key_id\x18\x01 \x01(\x03\x12\x0f\n\x07some_id\x18\x02 \x01(\x03\x12\x12\n\naccount_id\x18\x03 \x01(\t\x12\n\n\x02IV\x18\x04 \x01(\x0c\x12\x1b\n\x13user_encrypted_data\x18\x05 \x01(\x0c\"\xa0\x01\n\x14SessionType33Message\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0bsign_key_id\x18\x02 \x01(\x03\x12\x0e\n\x06region\x18\x03 \x01(\t\x12\x0f\n\x07\x44\x45R_Sig\x18\x04 \x01(\x0c\x12\x17\n\x04user\x18\x05 \x01(\x0b\x32\t.UserInfo\x12\x19\n\x11\x63reation_unixtime\x18\x06 \x01(\r\x12\x10\n\x08\x61ux_data\x18\x07 \x01(\x0c\"\x92\x01\n\x14SessionType23Message\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x0e\x65ncrypt_key_id\x18\x02 \x01(\x03\x12\n\n\x02IV\x18\x03 \x01(\x0c\x12\x1b\n\x13user_encrypted_data\x18\x04 \x01(\x0c\x12\x19\n\x11\x63reation_unixtime\x18\x05 \x01(\r\x12\x10\n\x08unknown3\x18\x06 \x01(\x0c\"\x80\x01\n\x14SessionType21Message\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x0e\x65ncrypt_key_id\x18\x02 \x01(\x03\x12\n\n\x02IV\x18\x03 \x01(\x0c\x12\x1b\n\x13user_encrypted_data\x18\x04 \x01(\x0c\x12\x19\n\x11\x63reation_unixtime\x18\x05 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aws_session_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERINFO']._serialized_start=21
  _globals['_USERINFO']._serialized_end=133
  _globals['_SESSIONTYPE33MESSAGE']._serialized_start=136
  _globals['_SESSIONTYPE33MESSAGE']._serialized_end=296
  _globals['_SESSIONTYPE23MESSAGE']._serialized_start=299
  _globals['_SESSIONTYPE23MESSAGE']._serialized_end=445
  _globals['_SESSIONTYPE21MESSAGE']._serialized_start=448
  _globals['_SESSIONTYPE21MESSAGE']._serialized_end=576
# @@protoc_insertion_point(module_scope)
